apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator
  namespace: default  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-generator
  template:
    metadata:
      labels:
        app: password-generator
    spec:
      containers:
      - name: password-generator
        image: password-generator:latest
        ports:
        - containerPort: 8080
