apiVersion: v1
kind: Service
metadata:
  name: password-generator-service
  namespace: default  
spec:
  selector:
    app: password-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
